version: '3.3'
services:
  craftcms:
    build: .
    env_file:
      - .env
    restart: always
    volumes:
      - ./html/assets:/var/www/html/web/assets:z
      - ./html/backups:/var/www/html/storage/backups
      - ./html/templates:/var/www/html/templates
      - ./html/translations:/var/www/html/translations
      - ./html/redactor:/var/www/html/config/redactor
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.craftcms-http.rule=Host(`craft.example.com`)
      - traefik.http.routers.craftcms-http.entrypoints=http
      - traefik.http.routers.craftcms-http.middlewares=https-redirect
      - traefik.http.routers.craftcms-https.rule=Host(`craft.example.com`)
      - traefik.http.routers.craftcms-https.entrypoints=https
      - traefik.http.routers.craftcms-https.tls=true
      - traefik.http.routers.craftcms-https.tls.certresolver=le
      - traefik.http.services.craftcms.loadbalancer.server.port=8080
    depends_on:
      - db

  db:
    image: mariadb:10
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - traefik-public
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: examplepass

networks:
  traefik-public:
    external: true
